### ISSUE TITLE
"exclude" is not a valid field for `<profile>.sign.path.<PATH>` scope

### ISSUE THREAD

**Issue by nikitalita** [indygreg/apple-platform-rs#186]
Even though the [documentation states that you can exclude a path via the config file](https://gregoryszorc.com/docs/apple-codesign/stable/apple_codesign_rcodesign_config_files.html#sign-command-settings), it's not actually possible to do so because the parser does not actually have that as a valid field.

trying to sign with `rcodesign sign` results in:
```
  source path: ./rcodesign.toml
  in profile: default
  problem key: sign, path, *.a, exclude
  problem: UnknownField("exclude", ["binary_identifier", "code_requirements_file", "code_resources_file", "code_signature_flags", "digests", "entitlements_xml_file", "launch_constraints_self_file", "launch_constraints_parent_file", "launch_constraints_responsible_file", "library_constraints_file", "runtime_version", "info_plist_file"])
```

using this config:

```toml
[default]
[default.sign.path."*.dylib"]
entitlements_xml_file = "misc/editor_debug.entitlements"

[default.sign.path."*.a"]
exclude = true

[default.sign]
signer.macos_keychain = { sha256_fingerprint = "<SIG>" }
```
